### ISSUE TITLE
Tracked LMPs throw an exception of the client does not actually stream the response

### ISSUE THREAD

**Issue by Nitewriter** [MadcowD/ell#175]
I was trying to connect to an OpenAI-like API through LiteLLM. If I disable tracking for the LMP, it seems to work fine, but the tracking stuff is awesome, so I would like to keep it enabled.

**Sample Code**

```python
import ell
from openai import OpenAI

ell.init(verbose=True)


litellm_client = OpenAI(
    api_key="my-api-key",
    base_url="https://my-litellm-proxy.com",
)


@ell.simple(
    model="gpt-4o",
    temperature=1.0,
    client=litellm_client,
)
def say_hello(name: str):
    """You are a surfer dude. Say hello to the user."""
    return f"Hello, I'm {name}!"


if __name__ == "__main__":
    reply = say_hello("John")
    print(reply)
```

**Error**

```bash
❯ poetry run python -m src.chatbot
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ say_hello(John)
╠════════════════════════════════════════════════════════════════════════════════════════════════╣
║ Prompt:
╟────────────────────────────────────────────────────────────────────────────────────────────────╢
│      system: You are a surfer dude. Say hello to the user.
│
│        user: Hello, I'm John!
╟────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Output:
╟────────────────────────────────────────────────────────────────────────────────────────────────╢
│   assistant: Hey there, John! Stoked to meet ya, dude! 🌊 How's it hangin'? Catchin'
│              any good waves lately?Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/path/to/project/src/chatbot/__main__.py", line 24, in <module>
    reply = say_hello("John")
            ^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/ell/lmp/_track.py", line 64, in tracked_func
    return func_to_track(*fn_args, **fn_kwargs, _invocation_origin=invocation_id)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/ell/lmp/complex.py", line 241, in model_call
    (result, _api_params, metadata) = call(model=model, messages=messages, api_params={**config.default_lm_params, **api_params, **lm_params}, client=client or default_client_from_decorator, _invocation_origin=_invocation_origin, _exempt_from_tracking=exempt_from_tracking, _logging_color=color, _name=prompt.__name__, tools=tools)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/ell/util/api.py", line 55, in call
    tracked_results, metadata = provider_class.process_response(call_result, _invocation_origin, _logger if config.verbose and not _exempt_from_tracking else None, tools)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/.venv/lib/python3.12/site-packages/ell/providers/openai.py", line 223, in process_response
    Message(
  File "/path/to/project/.venv/lib/python3.12/site-packages/ell/types/message.py", line 196, in __init__
    super().__init__(content=content, role=role)
  File "/path/to/project/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Message
role
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
```

**Comment by MadcowD** [comment]
nice havent tested with litellm yet 
can you go to ` "/path/to/project/.venv/lib/python3.12/site-packages/ell/providers/openai.py",` line 223 & print out  whats being passed to Message? Maybe role is none or content not sure. I dont have litellm set up

**Comment by Nitewriter** [comment]
Ok, so I don't know if the tracking is the cause. It seems LiteLLM may handle streaming a bit weirdly and that may be causing ell to break.

**Comment by Nitewriter** [comment]
Ok, this is what I'm seeing when it fails for that openai.py line 223.

```
choice=Choice(delta=ChoiceDelta(content=None, function_call=None, refusal=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=None) 
call_result.actual_streaming=True
```

So I would expect it to be using the `choice_deltas[0].delta.role`, but that doesn't appear to be available.

**Comment by MadcowD** [comment]
Omg LiteLLM strikes again. Can you investigate and see if litellm ever sends a role back 😢 if not mkae a pr that assumes the role is "assistant" if its not there maybe..

**Comment by Nitewriter** [comment]
Yes, it does eventually send the role back. I patched it in place to default to `assistant` and that worked.

**Comment by Nitewriter** [comment]
@MadcowD put a PR together https://github.com/MadcowD/ell/pull/182
