### ISSUE TITLE
lexical closure using proto source

### ISSUE THREAD

**Issue by MadcowD** [MadcowD/ell#248]
Traceback (most recent call last):
  File "/Users/brnaba/Documents/github/ell-bedrock-support-fork/.venv/lib/python3.12/site-packages/ell/util/closure.py", line 186, in _process_signature_dependency
    dep, _, _uses = lexical_closure(type(val), already_closed=already_closed, recursion_stack=recursion_stack.copy())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brnaba/Documents/github/ell-bedrock-support-fork/.venv/lib/python3.12/site-packages/ell/util/closure.py", line 98, in lexical_closure
    module_src = _process_modules(modules, cur_src, already_closed, recursion_stack, uses)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brnaba/Documents/github/ell-bedrock-support-fork/.venv/lib/python3.12/site-packages/ell/util/closure.py", line 254, in _process_modules
    attrs_to_extract = get_referenced_names(cur_src.replace(DELIM, ""), mname)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brnaba/Documents/github/ell-bedrock-support-fork/.venv/lib/python3.12/site-packages/ell/util/closure.py", line 351, in get_referenced_names
    tree = ast.parse(code)
           ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 3
    _DefaultValues = <dict object>
                     ^
SyntaxError: invalid syntax

**Comment by MadcowD** [comment]
The real issue that @brnaba is having is that somehow pydantic is getting serialized :(
