### ISSUE TITLE
AttributeError: 'Groq' object has no attribute 'beta' when using ELL with Groq client

### ISSUE THREAD

**Issue by aandresalvarez** [MadcowD/ell#253]
**Description:**

I'm encountering an `AttributeError` when trying to use the ELL library with the Groq client. The error occurs when invoking a function decorated with `@ell.complex`.

**Steps to Reproduce:**

1. Set up the environment variable `GROQ_API_KEY` with a valid API key.
2. Run the following minimal code:

```python
# minimal_error_reproduction.py

import os
import ell
import groq

# Initialize ELL with verbose logging
ell.init(verbose=True)

# Retrieve Groq API key from environment variable
groq_api_key = os.getenv('GROQ_API_KEY')
if not groq_api_key:
    raise EnvironmentError("GROQ_API_KEY environment variable not set.")

# Initialize Groq client
client = groq.Groq(api_key=groq_api_key)

# Register the Groq client with ELL
ell.models.groq.register(client)

# Define a simple Pydantic model for structured output
from pydantic import BaseModel

class SimpleResponse(BaseModel):
    message: str

# Use @ell.complex with the Groq model
@ell.complex(model="llama3-8b-8192", response_format=SimpleResponse)
def test_function():
    return "Return a JSON object with a 'message' field containing 'Hello, world!'"

# Invoke the function
response_message = test_function()
print(response_message.parsed)
```

**Expected Behavior:**

The `test_function` should return a parsed `SimpleResponse` object containing the message "Hello, world!".

**Actual Behavior:**

An `AttributeError` is raised:

```
AttributeError: 'Groq' object has no attribute 'beta'
```

**Full Traceback:**

```
Traceback (most recent call last):
  File "minimal_error_reproduction.py", line 36, in <module>
    response_message = test_function()
  File ".../ell/lmp/_track.py", line 64, in tracked_func
    return func_to_track(*fn_args, **fn_kwargs, _invocation_origin=invocation_id)[0]
  File ".../ell/lmp/complex.py", line 68, in model_call
    (result, final_api_params, metadata) = provider.call(ell_call, origin_id=_invocation_origin, logger=_logger if should_log else None)
  File ".../ell/provider.py", line 121, in call
    call = self.provider_call_function(ell_call.client, final_api_call_params)
  File ".../ell/providers/openai.py", line 25, in provider_call_function
    return client.beta.chat.completions.parse
AttributeError: 'Groq' object has no attribute 'beta'
```

**Environment:**

- Python version: 3.11
- ELL version: 0.0.12
- Groq version: 0.11.0

**Additional Information:**

It appears that the ELL library is attempting to access the `beta` attribute on the Groq client, which doesn't exist. This might indicate a compatibility issue or a misconfiguration in how ELL interacts with the Groq client.

---

**Request:**

Could you please look into this issue? Let me know if additional information is needed to diagnose the problem.

**Comment by MadcowD** [comment]
Can you upgrade your ell? Or what version are you on?

**Comment by MadcowD** [comment]
```
from groq import Groq

client = Groq()
completion = client.chat.completions.create(
model="llama3-8b-8192",
messages=[
{
"role": "system",
"content": "Please respond in json"
},
{
"role": "user",
"content": ""
}
],
temperature=1,
max_tokens=1024,
top_p=1,
stream=False,
response_format={"type": "json_object"},
stop=None,
)

print(completion.choices[0].message)
```
works for me on 0.0.12!

**Comment by MadcowD** [comment]
```
pip install --upgrade ell-ai
```

**Comment by idvorkin** [comment]
This issue still exists if you try to pass a complex response format - e.g. 

```python
@ell.complex(
        model=get_ell_model(llama=True),
        response_format=ImageRecognitionResult,
)  
```

Is this expected? If so, could we throw a more descriptive error?

**Comment by idvorkin** [comment]
@MadcowD ^
