### ISSUE TITLE
Cannot import FilesystemSerializer

### ISSUE THREAD

**Issue by tianyaohu** [MadcowD/ell#3]
```
ell/examples/serialization_example.py
Traceback (most recent call last):
  File "d:\dev\ell\examples\serialization_example.py", line 7, in <module>
    from ell.stores.jsonl import FilesystemSerializer
ImportError: cannot import name 'FilesystemSerializer' from 'ell.stores.jsonl' (D:\dev\ell\ell\src\ell\stores\jsonl.py)
```

**Comment by MadcowD** [comment]
Yep, we use SQLiteStore now. Sorry for all the dust I'm gonna do some clean up today!

**Comment by tianyaohu** [comment]
Just pulled the latest update from main.
a826283 (HEAD -> main, origin/main, origin/HEAD) kind of working setup.py

Now most of the examples are complaining about ell.stores.jsonl
```
(ell_lab) D:\dev\ell>D:/anaconda/envs/ell_lab/python.exe d:/dev/ell/examples/lexical_closure_example.py
Traceback (most recent call last):
  File "d:\dev\ell\examples\lexical_closure_example.py", line 1, in <module>
    from ell.util.closure import lexically_closured_source
ModuleNotFoundError: No module named 'ell.util.closure'


#jokes, hello world all shows this.
(ell_lab) D:\dev\ell>D:/anaconda/envs/ell_lab/python.exe d:/dev/ell/examples/multilmp.py
Traceback (most recent call last):
  File "d:\dev\ell\examples\multilmp.py", line 4, in <module>
    from ell.stores.sql import SQLiteStore
ModuleNotFoundError: No module named 'ell.stores.sql'
```

**Comment by MadcowD** [comment]
on it

**Comment by MadcowD** [comment]
we swtiched off of poetry:
```
pip uninstall ell
pip install -e .
```
in the main directory
