### ISSUE TITLE
Can't use instructor provider with openrouter

### ISSUE THREAD

**Issue by olafgeibig** [MadcowD/ell#306]
The instructor example works well (if the instructor library is patched according to https://github.com/MadcowD/ell/issues/304). It fails if I replace the OpenAI model with the API compatible openrouter client. The problem might apply also for other OpenAI API compatible model providers.

Code:
```python
import ell
from openai import OpenAI
import os
from pydantic import BaseModel, Field
from dotenv import load_dotenv
import instructor

from typing import Any, Callable, Dict, Optional, Tuple, cast
from ell.provider import EllCallParams, Metadata, Provider
from ell.providers.openai import OpenAIProvider
from ell.types.message import ContentBlock, Message

load_dotenv()
ell.init(store='./logdir', autocommit=True)

# Initialize OpenAI client with OpenRouter's base URL and API key
openrouter_client = instructor.from_openai(OpenAI(
    api_key=os.getenv("OPENROUTER_API_KEY"),
    base_url="https://openrouter.ai/api/v1",
))

class InstructorProvider(OpenAIProvider):
    def translate_to_provider(self, *args, **kwargs):
        """ This translates ell call param,eters to the provider call parameters.  IN this case instructor is jsut an openai client. 
        so we can use the openai provider to do the translation. We just need to modify a few parameters because instructor doesn't support streaming."""
        api_params= super().translate_to_provider(*args, **kwargs)
        # Streaming is not allowed by instructor.
        api_params.pop("stream", None)
        api_params.pop("stream_options", None)
        return api_params
    
    def translate_from_provider(self,provider_response,
            ell_call : EllCallParams,
            provider_call_params : Dict[str, Any],
            origin_id : str, 
            logger : Optional[Callable] = None) -> Tuple[Message, Metadata]:
        """This translates the provider response (the result of calling client.chat.completions.create with the parameters from translate_to_provider)
          to an an ell message. In this case instructor just returns a pydantic type which we can use to create an ell response model. """
        instructor_response = cast(BaseModel, provider_response) # This just means that the type is a pydantic BaseModel. 
        if logger: logger(instructor_response.model_dump_json()) # Don't forget to log for verbose mode!
        return Message(role="assistant", content=ContentBlock(parsed=instructor_response)), {}

# We then register the provider with ell. We will use InstructorProvider any time an instructor.Instructor type client is used.
ell.register_provider(InstructorProvider(), instructor.Instructor)

class MovieReview(BaseModel):
    title: str = Field(description="The title of the movie")
    rating: int = Field(description="The rating of the movie out of 10")
    summary: str = Field(description="A brief summary of the movie")

@ell.complex(model="google/gemini-flash-1.5-exp", client=openrouter_client, response_format=MovieReview)#, extra_body=extra_body)
def generate_movie_review(movie: str) -> MovieReview:
    """You are a movie review generator. Given the name of a movie, you need to return a structured review."""
    return f"generate a review for the movie {movie}"

response = generate_movie_review("The Matrix")
print(response)
```
Output:
```
Traceback (most recent call last):
  File "/Users/GEO5BE4/work/ai-experiments/ell-test/ell_test/json_openrouter.py", line 70, in <module>
    response = generate_movie_review("The Matrix")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GEO5BE4/work/ai-experiments/ell-test/.venv/lib/python3.12/site-packages/ell/lmp/_track.py", line 118, in tracked_func
    else func_to_track(*fn_args, _invocation_origin=invocation_id, **fn_kwargs, )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GEO5BE4/work/ai-experiments/ell-test/.venv/lib/python3.12/site-packages/ell/lmp/complex.py", line 68, in model_call
    (result, final_api_params, metadata) = provider.call(ell_call, origin_id=_invocation_origin, logger=_logger if should_log else None)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GEO5BE4/work/ai-experiments/ell-test/.venv/lib/python3.12/site-packages/ell/provider.py", line 121, in call
    call = self.provider_call_function(ell_call.client, final_api_call_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/GEO5BE4/work/ai-experiments/ell-test/.venv/lib/python3.12/site-packages/ell/providers/openai.py", line 25, in provider_call_function
    return client.beta.chat.completions.parse
           ^^^^^^^^^^^
AttributeError: 'Instructor' object has no attribute 'beta'
```

**Comment by reecelikesramen** [comment]
Ah, this is subtle and kind of an annoying thing. OpenAI's API param name for its parsed JSON response beta is `response_format`. Since your `generate_movie_review` is from the ell docs, its using that because in that example its using GPT-4. Instructor's API param name is `response_model` which you can see [on their Github repo](https://github.com/instructor-ai/instructor) and in the `@ell.complex` call in `instructor_ex.py`

@olafgeibig TLDR I copied your code and changed `response_format` to `response_model` and it worked fine.
