### ISSUE TITLE
Circular Import Issues on Mac

### ISSUE THREAD

**Issue by 0xThresh** [MadcowD/ell#324]
I've run into this issue on two separate Mac machines. 

Machine 1:
M2 MacBook Pro
macOS 14.7
Darwin 23.6.0
Python version 3.11.1
Pip version 24.2

Machine 2: 
M2 MacBook Pro
macOS 15.0.1
Darwin 24.0.0
Python version 3.12.6
Pip version 24.2

I've tried using fresh virtual environments, and even downloaded Conda and initialized a new environment through that to install ell. Regardless of how I tried to install, I continuously ran into the issue below on both of my Macs: 
```
Traceback (most recent call last):
  File "ell-test/ell.py", line 1, in <module>
    import ell
  File "ell-test/ell.py", line 3, in <module>
    @ell.simple(model="gpt-4o")
     ^^^^^^^^^^
AttributeError: partially initialized module 'ell' has no attribute 'simple' (most likely due to a circular import)
```

The code I'm running is a direct copy from the quickstart: 
```
import ell

@ell.simple(model="gpt-4o")
def hello(name: str):
    """You are a helpful assistant.""" # System prompt
    return f"Say hello to {name}!" # User prompt

greeting = hello("0xThresh")
print(greeting)
```

I was able to install and use ell successfully on a machine using WSL, so the issue does seem unique to Macs. I've heard in the Discord server that others are using Macs without issue, but I'm not sure how I'm experiencing the same issue across two separate machines. I'd greatly appreciate any help resolving the issue and would be happy to provide further information if needed.

**Comment by 0xThresh** [comment]
Upon running into the issue on Windows, I realized that this was because I've been consistently naming my test file `ell.py`. As soon as I renamed the file this issue disappeared. Hopefully this saves someone else some trouble!
