### ISSUE TITLE
Evaluation - ValueError: Invalid input type: <class 'str'> - Correction Found

### ISSUE THREAD

**Issue by brenorb** [MadcowD/ell#398]
Even after commenting out the `n_evals` variable in the evaluation example from the Studio Evaluation tab (which is an error I reported in https://github.com/MadcowD/ell/issues/397), I still got an error, now a `ValueError`.

```
basic-eval outputs:   0%|                                           | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/usr/code/evaluation.py", line 56, in <module>
    results = eval.run(mylmp)
              ^^^^^^^^^^^^^^^
  File "/Users/usr/code/.venv/lib/python3.11/site-packages/ell/evaluation/evaluation.py", line 180, in run
    get_outputs = future.result()
                  ^^^^^^^^^^^^^^^
  File "/Users/usr/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/usr/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/usr/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usr/code/.venv/lib/python3.11/site-packages/ell/evaluation/evaluation.py", line 222, in _process_single
    lmp_output = get_lmp_output(data_point, lmp, lmp_params_with_invocation_id, required_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/usr/code/.venv/lib/python3.11/site-packages/ell/evaluation/util.py", line 26, in get_lmp_output
    raise ValueError(f"Invalid input type: {type(inp)}")
ValueError: Invalid input type: <class 'str'>
```

The example is from the Evaluation tab in Studio is:

```python
import ell
from ell import Evaluation

@ell.simple(model="gpt-4o")
def mylmp(greeting: str):
    return f"Say hi there!"

def metric(datapoint, output):
    return 1 if output == "Hi there!" else 0

# Initialize your evaluation
eval = Evaluation(
    name="basic-eval",
    dataset=[{"input": "Hello", "expected": "Hi there!"}],
    # n_evals=10,
    metrics={"score": metric},
)

# Run the evaluation
results = eval.run(mylmp)
```

## PS: just found a way to make it work

Now we need decide whether to fix the example or the code.

```python
# This doesn't work and raises a ValueError
dataset=[{"input": "Hello", "expected": "Hi there!"}],
# This works fine. It expects a list or a dictionary
dataset=[{"input": ["Hello"], "expected": "Hi there!"}],
# This also works
dataset=[{"input": {"greeting": "Hello"}, "expected": "Hi there!"}],
```

**Comment by MadcowD** [comment]
Thanks for finding this. I didn't set it up to take a single input because you wouldn't know if the first argument of the LMP was a list type or if you meant a list of arguments.

**Comment by brenorb** [comment]
No problem. Since it seems we're in the same page, I created PR https://github.com/MadcowD/ell/pull/400, that will fix this issue together with https://github.com/MadcowD/ell/issues/397 taking the simplest approach: correcting the example.

**Comment by brenorb** [comment]
PR https://github.com/MadcowD/ell/pull/400 merged.
