### ISSUE TITLE
examples/multilmp.py

### ISSUE THREAD

**Issue by tianyaohu** [MadcowD/ell#4]
```
(ell_lab) D:\dev\ell>D:/anaconda/envs/ell_lab/python.exe d:/dev/ell/examples/multilmp.py
before ideas 1232131
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ generate_story_ideas(a dog) # (notimple...)
╠═════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
║ Prompt:
╟─────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
│      system: You are an expert story ideator. Only answer in a single sentence.
│
│        user: Generate a story idea about a dog.
╟─────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
║ Output[0 of 4]:
╟─────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
│   assistant: A rescue dog with the ability to sense emotions helps a grieving child heal after the
│              loss of a loved one, leading them both on a journey of friendship and discovery.
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "d:\dev\ell\examples\multilmp.py", line 53, in <module>
    story = write_a_really_good_story("a dog")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 207, in wrapper
    else fn(*fn_args, _invocation_origin=invocation_id, **fn_kwargs, )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 150, in wrapper
    res = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\dev\ell\examples\multilmp.py", line 32, in write_a_really_good_story
    ideas = generate_story_ideas(about, lm_params=(dict(n=4)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 216, in wrapper
    fn_closure, _uses = ell.util.closure.lexically_closured_source(func_to_track)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\util\closure.py", line 306, in lexically_closured_source
    _, fnclosure, uses = lexical_closure(func, initial_call=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\util\closure.py", line 250, in lexical_closure
    dep, _,  dep_uses = lexical_closure(
                        ^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\util\closure.py", line 196, in lexical_closure
    ret = lexical_closure(
          ^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\util\closure.py", line 140, in lexical_closure
    source = getsource(func, lstrip=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\dill\source.py", line 374, in getsource
    lines, lnum = getsourcelines(object, enclosing=enclosing)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\dill\source.py", line 345, in getsourcelines
    code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\dill\source.py", line 271, in getblocks
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\dill\source.py", line 215, in findsource
    line = lines[lnum]
           ~~~~~^^^^^^
IndexError: list index out of range

```

**Comment by MadcowD** [comment]
Oh this is super interesting. What system are you working on so Ican try and reproduce it. What python implementation are you using?

**Comment by tianyaohu** [comment]
## System info:
- **System**: Windows 11
- **Version**: 10.0.22631
- **Machine**: AMD64
- **Processor**: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
- **Architecture**: (64bit, WindowsPE)
- **Python Version**: 3.12.4

Here is the conda env file to reproduce environment [env.txt](https://github.com/user-attachments/files/16401318/env.txt)
Change extension to yaml. Git issue doesn't allow .yaml format

**Comment by MadcowD** [comment]
https://discord.com/invite/J2UhksbE Come join here and let's chat!

**Comment by MadcowD** [comment]
Fixed
