### ISSUE TITLE
Out of date doc reference in ImportError raised 

### ISSUE THREAD

**Issue by apandy02** [MadcowD/ell#402]
The docs page referenced in the following error no longer exists at the specified location:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ap/ell/src/ell/__init__.py", line 9, in <module>
    from ell.evaluation import Evaluation
  File "/Users/ap/ell/src/ell/evaluation/__init__.py", line 1, in <module>
    from ell.evaluation.evaluation import Evaluation
  File "/Users/ap/ell/src/ell/evaluation/evaluation.py", line 14, in <module>
    from ell.evaluation.results import _ResultDatapoint, EvaluationResults
  File "/Users/ap/ell/src/ell/evaluation/results.py", line 6, in <module>
    from ell.stores.models.evaluations import EvaluationLabelerType
  File "/Users/ap/ell/src/ell/stores/__init__.py", line 4, in <module>
    raise ImportError("ell.stores has missing dependencies. Install them with `pip install -U ell-ai[sqlite]` or `pip install -U ell-ai[postgres]`. More info: https://docs.ell.so/installation/custom-installation")`

**Comment by MadcowD** [comment]
Could you make a PR for this?

@alex-dixon what do you thinl

**Comment by apandy02** [comment]
@MadcowD yeah it should be a fairly simple one line change. let me open one
