### ISSUE TITLE
ell.db generation failed after deletion. Is this normal?

### ISSUE THREAD

**Issue by tianyaohu** [MadcowD/ell#5]
```
(ell_lab) D:\dev\ell>D:/anaconda/envs/ell_lab/python.exe d:/dev/ell/examples/joke.py
Traceback (most recent call last):
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute      
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: serializedlmp.commit_message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\dev\ell\examples\joke.py", line 30, in <module>
    joke("minecraft") # <The joke>
    ^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 207, in wrapper
    else fn(*fn_args, _invocation_origin=invocation_id, **fn_kwargs, )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 150, in wrapper
    res = fn(*fn_args, **fn_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\dev\ell\examples\joke.py", line 23, in joke
    return f"Act out a full joke. Make your script {get_random_length()} words long. Here's the premise: {come_up_with_a_premise_for_a_joke_about(topic)}"
                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\decorators.py", line 222, in wrapper
    lmps = serializer.get_lmps(name=_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ell\ell\src\ell\stores\sql.py", line 115, in get_lmps
    results = session.exec(query).all()
              ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlmodel\orm\session.py", line 66, in exec
    results = super().execute(
              ^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\orm\session.py", line 2351, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\orm\session.py", line 2236, in _execute_internal 
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\orm\context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context  
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "D:\anaconda\envs\ell_lab\Lib\site-packages\sqlalchemy\engine\default.py", line 924, in do_execute      
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: serializedlmp.commit_message       
[SQL: SELECT serializedlmp.lmp_id, serializedlmp.name, serializedlmp.source, serializedlmp.dependencies, serializedlmp.created_at, serializedlmp.is_lm, serializedlmp.lm_kwargs, serializedlmp.num_invocations, serializedlmp.commit_message, serializedlmp.version_number, serializedlmpuses.lmp_using_id
FROM serializedlmp LEFT OUTER JOIN serializedlmpuses ON serializedlmp.lmp_id = serializedlmpuses.lmp_user_id   
WHERE serializedlmp.name = ? ORDER BY serializedlmp.created_at DESC]
[parameters: ('come_up_with_a_premise_for_a_joke_about',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by MadcowD** [comment]
oh yeah so i am actively changing the db schema while i work we aren't even at alpha yet, so you need to do a migration your db or just delete your .db file and recreate it :S

I'll build automatic migrations once we get to v0.0.1 <3
